const splashes = [
  "Hack the game with Nightmoon!",
  "Exploit your way to victory!",
  "Nightmoon: Beyond the limits!",
  "Unleash your power with Nightmoon!",
  "Breach the boundaries!",
  "Dominate with Nightmoon cheats!",
  "Elevate your gameplay!",
  "Hack smarter, not harder!",
  "Nightmoon: The ultimate exploit!",
  "Control the game with Nightmoon!",
  "Unleash hacks with precision!",
  "Nightmoon: Power in your hands!",
  "Hack with style!",
  "Nightmoon: The hacker’s choice!",
  "Break the rules with Nightmoon!",
  "Nightmoon: Elite hacking tools!",
  "Exploit every opportunity!",
  "Master the game with Nightmoon!",
  "Hack like a pro!",
  "Nightmoon: Revolutionize your game!",
  "Achieve the impossible!",
  "Nightmoon: Hack the system!",
  "Your exploit, your rules!",
  "Unmatched Nightmoon power!",
  "Hack, dominate, win!",
  "Exploits for every challenge!",
  "Nightmoon: Beyond imagination!",
  "Take control with Nightmoon!",
  "Revolutionize your hacks!",
  "Nightmoon: The ultimate advantage!",
  "Break through barriers!",
  "Hack beyond limits!",
  "Nightmoon: Elevate your game!",
  "Exploit with Nightmoon power!",
  "Ultimate hacking experience!",
  "Dominate your opponents!",
  "Nightmoon: Redefine cheating!",
  "Hack with Nightmoon precision!",
  "The future of exploiting!",
  "Nightmoon: Your cheat companion!",
  "Master every exploit!",
  "Hack the game effortlessly!",
  "Nightmoon: Limitless possibilities!",
  "Unlock hidden powers!",
  "Unleash Nightmoon hacks!",
  "Dominate with Nightmoon tools!",
  "Ultimate gaming advantage!",
  "Hack beyond the ordinary!",
  "Master exploits with Nightmoon!",
  "Nightmoon: Control your destiny!",
  "Exploits for every need!",
  "Take over the game!",
  "Nightmoon: The cheat revolution!",
  "Elevate your hacks!",
  "Nightmoon: The future of hacking!",
  "Cheat with confidence!",
  "Nightmoon: Revolutionize your play!",
  "Ultimate control with Nightmoon!",
  "Break all limits!",
  "Nightmoon: Your exploit solution!",
  "Hack beyond imagination!",
  "Dominate every challenge!",
  "Nightmoon: Redefine your game!",
  "Master the art of exploiting!",
  "Nightmoon: The hacker’s toolkit!",
  "Unleash the power of Nightmoon!",
  "Hack with precision!",
  "Nightmoon: Exploit every chance!",
  "Elevate your gameplay!",
  "The ultimate hacking edge!",
  "Nightmoon: Your cheat companion!",
  "Break the game’s limits!",
  "Nightmoon: The power of hacks!",
  "Unmatched Nightmoon control!",
  "Revolutionize your gameplay!",
  "Nightmoon: The exploit master!",
  "Hack like never before!",
  "The future of Nightmoon hacks!",
  "Unlock new levels!",
  "Dominate with precision!",
  "Nightmoon: Elite hacking tools!",
  "Master every exploit!",
  "Control the game effortlessly!",
  "Nightmoon: Your ultimate advantage!",
  "Hack with ease!",
  "Nightmoon: Beyond the limits!",
  "Exploit every opportunity!",
  "The ultimate hacking experience!",
  "Nightmoon: Redefine your play!",
  "Cheat with Nightmoon power!",
  "Master every challenge!",
  "The future of exploiting!",
  "Nightmoon: Your gaming edge!",
  "Hack with precision!",
  "Nightmoon: The ultimate exploit!",
  "Elevate your hacks!",
  "Unleash your potential!",
  "Nightmoon: Control the game!",
  "Revolutionize your hacks!",
  "Hack with confidence!",
  "Nightmoon: The cheat master!",
  "Exploit your way to victory!",
  "Unlock hidden powers with Nightmoon!",
  "Master every challenge!",
  "Nightmoon: Your ultimate exploit!",
  "Elevate your game with Nightmoon!",
  "The future of hacking is here!",
  "Nightmoon: The power to dominate!",
  "Exploit every chance!",
  "Hack with the best tools!",
  "Nightmoon: Your cheat advantage!",
  "Master every exploit effortlessly!",
  "Dominate with Nightmoon power!",
  "Unleash the ultimate hacks!",
  "Nightmoon: Beyond your imagination!",
  "The cheat revolution begins!",
  "Hack smarter, not harder!",
  "Nightmoon: Your ultimate tool!",
  "Exploit beyond the limits!",
  "Revolutionize your gameplay with Nightmoon!",
  "Nightmoon: The cheat you need!",
  "Hack with unparalleled precision!",
  "Master the game with Nightmoon!",
  "Unleash the power of hacks!",
  "Nightmoon: The future of cheating!",
  "Exploit every opportunity!",
  "Dominate your enemies!",
  "Nightmoon: Redefine your strategy!",
  "Hack with Nightmoon precision!",
  "The ultimate exploit tool!",
  "Master every challenge effortlessly!",
  "Nightmoon: Your cheat revolution!",
  "Elevate your gameplay with Nightmoon!",
  "Unleash your full potential!",
  "Nightmoon: Beyond your wildest dreams!",
  "Exploit your way to success!",
  "The future of Nightmoon hacks!",
  "Hack smarter, not harder!",
  "Nightmoon: Your ultimate advantage!",
  "Redefine the game with Nightmoon!",
  "Unlock the ultimate hacks!",
  "Master every exploit effortlessly!",
  "Dominate with Nightmoon tools!",
  "The cheat you’ve been waiting for!",
  "Nightmoon: The ultimate control!",
  "Exploit like never before!",
  "Elevate your hacks to new levels!",
  "Nightmoon: The future of gaming!",
  "Master every challenge with Nightmoon!",
  "Revolutionize your gameplay!",
  "Nightmoon: Beyond imagination!",
  "Hack with unparalleled ease!",
  "Exploit every chance with Nightmoon!",
  "The ultimate tool for hackers!",
  "Redefine your game with Nightmoon!",
  "Unleash the ultimate power!",
  "Nightmoon: Your gaming edge!",
  "Master every exploit with ease!",
  "Elevate your cheats!",
  "Nightmoon: The cheat revolution!",
  "Hack with precision and style!",
  "Exploit beyond limits!",
  "The future of Nightmoon is now!",
  "Unlock new opportunities!",
  "Nightmoon: Dominate every game!",
  "Master the ultimate cheats!",
  "Nightmoon: The power of exploiting!",
  "Elevate your gameplay with ease!",
  "Hack with Nightmoon power!",
  "Exploit like a pro!",
  "The ultimate hacking tool!",
  "Revolutionize your cheats!",
  "Nightmoon: Your ultimate solution!",
  "Unleash your full potential!",
  "Master every challenge with Nightmoon!",
  "Hack smarter with Nightmoon!",
  "Exploit beyond your wildest dreams!",
  "The future of hacking is here!",
  "Nightmoon: The ultimate advantage!",
  "Elevate your cheats with precision!",
  "Unlock the ultimate hacks!",
  "Master every exploit effortlessly!",
  "Nightmoon: The cheat you need!",
  "Revolutionize your gameplay!",
  "Hack with unparalleled ease!",
  "Nightmoon: Your cheat revolution!",
  "Exploit beyond imagination!",
  "The ultimate tool for gamers!",
  "Nightmoon: The future of exploiting!",
  "Master every challenge with ease!",
  "Unleash your full potential with Nightmoon!",
  "Elevate your gameplay to new heights!",
  "Hack smarter, not harder!",
  "Nightmoon: The ultimate tool for cheats!",
  "Exploit like never before!",
  "Nightmoon: The future of gaming!",
  "Master every challenge effortlessly!",
  "The ultimate power is here!",
  "Nightmoon: Your gaming edge!",
  "Hack with style and precision!",
  "Exploit your way to the top!",
  "Nightmoon: The cheat of champions!",
  "Elevate your hacks with Nightmoon!",
  "Master every exploit with ease!",
  "The future of exploiting begins now!",
  "Nightmoon: Redefine your gameplay!",
  "Unleash the ultimate power with Nightmoon!",
  "Hack beyond limits!",
  "Nightmoon: Your ultimate gaming tool!",
  "Exploit every opportunity with precision!",
  "The cheat revolution starts here!",
  "Nightmoon: Dominate with ease!",
  "Master the ultimate hacks effortlessly!",
  "Elevate your cheats with Nightmoon!",
  "Unleash your full potential now!",
  "Nightmoon: The cheat you’ve been waiting for!",
  "Hack smarter, not harder!",
  "Exploit beyond imagination with Nightmoon!",
  "Master every challenge with precision!",
  "Nightmoon: The ultimate power!",
  "Revolutionize your game!",
  "Nightmoon: The future of hacking!",
  "Hack with unparalleled control!",
  "Unleash the power of Nightmoon!",
  "Master every exploit effortlessly!",
  "Elevate your gameplay with Nightmoon!",
  "The ultimate hacking tool!",
  "Exploit every chance with precision!",
  "Nightmoon: Dominate every game!",
  "The future of Nightmoon is here!",
  "Hack with style and precision!",
  "Unlock your full potential!",
  "Nightmoon: The cheat of champions!",
  "Master every challenge with ease!",
  "Exploit like never before!",
  "Revolutionize your gameplay with Nightmoon!",
  "Elevate your hacks to new heights!",
  "Nightmoon: The ultimate gaming advantage!",
  "Unleash your potential with Nightmoon!",
  "Hack beyond imagination!",
  "The ultimate tool for hackers!",
  "Nightmoon: Redefine your game!",
  "Exploit every opportunity effortlessly!",
  "Master every exploit with precision!",
  "Nightmoon: The cheat you need!",
  "Elevate your gameplay with ease!",
  "Unleash the ultimate hacks!",
  "Nightmoon: The future of exploiting!",
  "Hack smarter, not harder!",
  "Exploit like a pro with Nightmoon!",
  "The ultimate power in your hands!",
  "Revolutionize your hacks!",
  "Nightmoon: The ultimate cheat tool!",
  "Master every challenge effortlessly!",
  "Elevate your gameplay to new heights!",
  "Unleash your full potential with Nightmoon!",
  "Hack with precision and style!",
  "Nightmoon: The future of hacking!",
  "Wanted by floppy!",
  "Better than Horion!",
  "And another L for pro Realms!"
]